apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patches:
  # - path: deploy.yaml
  #   target:
  #     kind: Deployment
  #     name: webcompanion-deployment
  - path: service.yaml
    target:
      kind: Service
      name: webcompanion-service

namespace: webcompanion

images:
  - name: shittuay/webcompanion
    newTag: IMAGE_TAG

namePrefix: prod-
labels:
  - includeSelectors: true
    pairs:
      env: prod
      note: MAKE_SURE_TO_USE_WORKING_IMAGE

replicas:
  - name: webcompanion-deployment
    count: 3