apiVersion: v1
kind: Service
metadata:
  name: webcompanion-service
  namespace: webcompanion
spec:
  selector:
    app: webcompanion-deployment
  ports:
  - port: 5000
    targetPort: 5000
    nodePort: 30041
  type: NodePort
