apiVersion: v1
kind: Secret
metadata:
  name: webcompanion1-secrets
  namespace: webcompanion
type: Opaque
data:
   OPENAI_API_KEY: c2stcHJvai1WWEV2TnAwVHllU2tsNm5zTEJPYlQzQmxia0ZKMVB0ZjUzMGwwYUE1aTlrem5XTGIK
   PAGESPEED_API_KEY: QUl6YVN5QmVUaWQ5QUlJcmZfeFl4eW5iUklTTFFoU1h3Y1lKS2tvCg==