apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patches:
  # - path: deploy.yaml
  #   target:
  #     kind: Deployment
  #     name: webcompanion-deployment
  - path: service.yaml
    target:
      kind: Service
      name: webcompanion-service

namespace: webcompanion

images:
  - name: shittuay/webcompanion
    newTag: IMAGE_TAG

namePrefix: dev-
labels:
  - includeSelectors: true
    pairs:
      env: dev
      message: DO NOT USE IN PRODUCTION