# name: Webcompanion CI/CD Pipeline

name: Branch Protection

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - dev
      - qa
      - prod

jobs:
  branch_protection:
    runs-on: ubuntu-latest
    steps:
      - name: Check branch protection
        run: |
          echo "GITHUB_EVENT_NAME: $GITHUB_EVENT_NAME"
          echo "GITHUB_REF: $GITHUB_REF"
          
          if [[ $GITHUB_EVENT_NAME == "push" ]]; then
            BRANCH_NAME=$(echo $GITHUB_REF | sed 's#refs/heads/##')
            echo "BRANCH_NAME (push): $BRANCH_NAME"
            if [[ $BRANCH_NAME == "dev" || $BRANCH_NAME == "qa" || $BRANCH_NAME == "prod" ]]; then
              echo "Push denied. You can't push directly to $BRANCH_NAME branch"
              exit 1
            fi
          elif [[ $GITHUB_EVENT_NAME == "pull_request" ]]; then
            BASE_BRANCH=$(jq -r '.pull_request.base.ref' < $GITHUB_EVENT_PATH)
            echo "BASE_BRANCH (pull_request): $BASE_BRANCH"
            # No need to deny PRs, they should be reviewed and merged via the PR process
          fi


